#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LeftPair,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RightPair,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontArmMotor, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rearArmMotor,  tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    RightGripper,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    LeftGripper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    SuckyLeft,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_4,    SuckyRight,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define FRONT_ARM_MOTOR_RATE_LOW    25
#define FRONT_ARM_MOTOR_RATE_HIGH   100

#define REAR_ARM_MOTOR_RATE_LOW     25
#define REAR_ARM_MOTOR_RATE_HIGH    40

#define DRIVE_MOTOR_RATE_LOW        20
#define DRIVE_MOTOR_RATE_HIGH       100


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void driveInches(int distance)
{
  /* drive distance inches in a straight line. distance can be
     positive or negative */

  int rightMotorPower, leftMotorPower;
  int driveTime;                /* in mSec */

  if (distance > 0) {
    rightMotorPower = DRIVE_MOTOR_RATE_HIGH;
    leftMotorPower = DRIVE_MOTOR_RATE_HIGH;
  } else {
    rightMotorPower = - DRIVE_MOTOR_RATE_HIGH;
    leftMotorPower = -DRIVE_MOTOR_RATE_HIGH;
  }

  driveTime = distance*38;

  motor[RightPair] = rightMotorPower;
  motor[RightFront] = rightMotorPower;
  motor[LeftPair] = leftMotorPower;
  motor[LeftFront] = leftMotorPower;
  wait1Msec(driveTime);
  motor[RightPair] = 0;
  motor[RightFront] = 0;
  motor[LeftPair] = 0;
  motor[LeftFront] = 0;
}

void spinDegrees(int degrees)
{
  /* Spin robot degrees degrees. Positive is clockwise,
     negative is counterclockwise */

  int rightMotorPower, leftMotorPower;
  int spinTime;                /* in mSec */

  if (degrees > 0) {
    rightMotorPower = -DRIVE_MOTOR_RATE_HIGH;
    leftMotorPower = DRIVE_MOTOR_RATE_HIGH;
  } else {
    rightMotorPower = DRIVE_MOTOR_RATE_HIGH;
    leftMotorPower = -DRIVE_MOTOR_RATE_HIGH;
  }

  spinTime = degrees*8;

  motor[RightPair] = rightMotorPower;
  motor[RightFront] = rightMotorPower;
  motor[LeftPair] = leftMotorPower;
  motor[LeftFront] = leftMotorPower;
  wait1Msec(spinTime);
  motor[RightPair] = 0;
  motor[RightFront] = 0;
  motor[LeftPair] = 0;
  motor[LeftFront] = 0;
}


task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  motor[rearArmMotor] = REAR_ARM_MOTOR_RATE_HIGH;
  wait10Msec(40);
  motor[frontArmMotor] = -FRONT_ARM_MOTOR_RATE_HIGH;
  wait10Msec(30);
  motor[rearArmMotor] = REAR_ARM_MOTOR_RATE_LOW;
  wait10Msec(40);
  motor[rearArmMotor] = 0;
  wait10Msec(118);
  motor[frontArmMotor] = -FRONT_ARM_MOTOR_RATE_LOW;
  wait10Msec(50);
  motor[frontArmMotor] = 0;

  driveInches(12);
  spinDegrees(90);

  while (true)
  {}
}
